services:

  mysql:
    image: mysql:8.0
    container_name: mysql-notas

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    volumes:
      - mysql_data:/var/lib/mysql

  notas:
    build: .
    container_name: notas

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "5000:5000"

    env_file:
      - .env

volumes:
  mysql_data: